<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>

<h1>Crear Grupo</h1>
<h1>Registro</h1>

<form action="index.php?login" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Usuario</label>
        <input type="text" class="form-control" name="user" id="name" aria-describedby="emailHelp"
               placeholder="Ingrese su nombre">
    </div>

    <div class="form-group">
        <label for="firstname">Nombre</label>
        <input type="text" class="form-control" name="firstname" id="firstname" aria-describedby="emailHelp"
               placeholder="Ingrese su nombre">
    </div>

    <div class="form-group">
        <label for="lastname">Apellidos</label>
        <input type="text" class="form-control" name="lastname" id="lastname" aria-describedby="emailHelp"
               placeholder="Ingrese su apellido">
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1">Contraseña</label>
        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1">Repita su contraseña</label>
        <input type="password" name="password2" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>

    <br>
    <input type="submit" name="registro" class="btn btn-primary" value="Entrar"/>
</form>

<!-- <h2>Logeo</h2>
<form action="index.php?login" method="post">
    <input type="text" name="user" placeholder="Usuario" />
    <input type="password" name="password" placeholder="Contraseña" />
    <input type="submit" name="logeo" value="Entrar" />
</form>

<h2>Registro</h2>
<form action="index.php?login" method="post">
    <input type="text" name="user" placeholder="Usuario" />
    <input type="password" name="password" placeholder="Contraseña" />
    <input type="password" name="password2" placeholder="Repite la contraseña" />
    <input type="submit" name="registro" value="Registro" />
</form> -->
</body>

</html>