<!DOCTYPE html>
<html>
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link href="views/css/style.css" rel="stylesheet">


    <script src="https://kit.fontawesome.com/61702239e8.js" crossorigin="anonymous"></script>
    <title>WhatsApp</title>

    <style>

    </style>

</head>
<body class="bg-secundary">
<h1 class="text-white">Ejemplo WhatsApp</h1>

<?php

//Declaramos login para el href del usuario
$login = null;

if (!$_SESSION['user']->getName()) {
    $login = 'index.php?login';
} else {
    $login = $_SESSION['user']->getName() . 'index.php?login&logout';
}

$is_admin = $_SESSION['user']->getRol();

foreach ($chats as $chat ) {
    $chat->getText();
    echo $chat;
}


?>

<footer class="footer bg-primary py-1">
    <div class="row h-100 mx-2">
        <div class="col-1 my-auto">
            <a href="<?php echo $login?>">
                <img class="img-user" src="views/img/users/<?php echo $_SESSION['user']->getImg();?> ">
            </a>
        </div>
        <div class="col-11 row px-0 mx-0">
            <div class="col-11 my-auto">
                <textarea name="message" class="h-75 w-100"></textarea>
            </div>
            <div class="col-1 my-auto">
                <h3 class="m-0 p-0"><i class="far fa-paper-plane text-white"></i></h3>
            </div>
        </div>

    </div>
</footer>

</body>
</html>
