<!DOCTYPE html>
<html>
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/61702239e8.js" crossorigin="anonymous"></script>
    <title>WhatsApp</title>

</head>
<body>
<h1>Ejemplo WhatsApp</h1>

<?php

if (!$_SESSION['user']->getName()) {
    echo '<a href="index.php?login">Login</a>';
} else {
    echo $_SESSION['user']->getName() . ' <a href="index.php?login&logout">Salir</a>';
}

$is_admin = $_SESSION['user']->getRol();

?>
</body>
</html>
